In [1]:
import tensorflow as tf

In [2]:
print(tf.add(1,2))
print(tf.add([1,2],[3,4]))


tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)


In [3]:
print(tf.square(5))

tf.Tensor(25, shape=(), dtype=int32)


In [4]:
print(tf.reduce_sum([1,2,3]))

tf.Tensor(6, shape=(), dtype=int32)


In [5]:
print(tf.reduce_sum([1,2,3,4]))

tf.Tensor(10, shape=(), dtype=int32)


In [6]:
print(tf.square(2) + tf.square(3))

tf.Tensor(13, shape=(), dtype=int32)


In [8]:
x = tf.matmul([[1]], [[2,3]])

In [9]:
print(x)

tf.Tensor([[2 3]], shape=(1, 2), dtype=int32)


In [10]:
x.shape

TensorShape([1, 2])

In [11]:
x.dtype

tf.int32

In [12]:
import numpy as np


In [13]:
ndarray = np.ones([3,3])

In [14]:
ndarray

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
tensor = tf.multiply(ndarray, 42)

In [16]:
print(tensor)

tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)


In [17]:
print(np.add(tensor, 1))

[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]


In [19]:
print(tensor.numpy())

[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]


In [20]:
tensor

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[42., 42., 42.],
       [42., 42., 42.],
       [42., 42., 42.]])>

In [21]:
print("Is there usable GPU.")
print(tf.config.experimental.list_physical_devices("GPU"))

print("GUP #0")
print(x.device.endswith('GPU:0'))


Is there usable GPU.
[]
GUP #0
False


In [22]:
dd = tf.random.uniform([10,10])

In [23]:
dd.numpy()

array([[0.9099221 , 0.6488581 , 0.6819775 , 0.8868135 , 0.24212682,
        0.71677244, 0.9212965 , 0.60819745, 0.9358468 , 0.7734277 ],
       [0.47971296, 0.4096768 , 0.919088  , 0.59603894, 0.2916559 ,
        0.15192735, 0.26327002, 0.96858335, 0.5531571 , 0.57231414],
       [0.4257977 , 0.5509093 , 0.1077764 , 0.25204074, 0.880404  ,
        0.6013416 , 0.12488234, 0.28968155, 0.13674748, 0.52751553],
       [0.43147624, 0.14470756, 0.17505729, 0.32862175, 0.3028543 ,
        0.21034002, 0.6732272 , 0.7607794 , 0.61910355, 0.6118299 ],
       [0.5793977 , 0.6097696 , 0.47411156, 0.28915727, 0.8380519 ,
        0.45270932, 0.989329  , 0.6443291 , 0.7994995 , 0.8167597 ],
       [0.5160284 , 0.04946578, 0.83828974, 0.5171062 , 0.8544494 ,
        0.29373848, 0.66926706, 0.99705744, 0.7427558 , 0.7367505 ],
       [0.8445115 , 0.04321122, 0.81164896, 0.8301431 , 0.6287724 ,
        0.5795605 , 0.03069222, 0.46162283, 0.5419371 , 0.86945736],
       [0.20440495, 0.48991537, 0.1097778

In [25]:
tf.zeros([10,5])

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [27]:
layer = tf.keras.layers.Dense(10, input_shape=(None, 5))

In [28]:
layer(tf.zeros([10,5]))

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [29]:
layer.variables

[<tf.Variable 'dense/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.561608  ,  0.06074166,  0.06916124, -0.47911292, -0.33465979,
          0.47902852, -0.5244888 , -0.5231551 , -0.26286092,  0.41788834],
        [ 0.12620974, -0.28393823,  0.6132515 , -0.5135746 , -0.0211491 ,
          0.15133244,  0.18357569, -0.4396336 ,  0.29808724,  0.36079997],
        [ 0.19873393, -0.23296893, -0.07604963, -0.0222559 , -0.50369227,
          0.0998019 ,  0.15933043, -0.5573539 , -0.03906375,  0.11928701],
        [ 0.5308402 ,  0.56210166,  0.50422364, -0.41373813,  0.38430947,
          0.3725968 ,  0.58865505, -0.26314303, -0.6283859 ,  0.6292493 ],
        [ 0.41334063, -0.5186515 , -0.56612396, -0.29649037, -0.52626425,
         -0.32426557, -0.32908645, -0.29005378,  0.190086  , -0.59185   ]],
       dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]