In [1]:
import tensorflow as tf

mnist = tf.keras.datasets.mnist

(x_train,y_train),(x_test,y_test) = mnist.load_data()
x_train, x_test = x_train/255.0, x_test/255.0


In [2]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2), tf.keras.layers.Dense(10)
])


In [5]:
x_train[:1]

array([[[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.

In [3]:
import matplotlib.pyplot as plt


In [4]:
predictions = model(x_train[:1]).numpy()
predictions


array([[ 0.05541504,  0.32819578, -0.17205141, -0.25640723, -0.29124   ,
         0.5127271 ,  0.07678033,  0.5512237 , -0.15130493, -0.5059644 ]],
      dtype=float32)

In [7]:
tf.nn.softmax(predictions).numpy()

array([[0.09826819, 0.12908629, 0.07827543, 0.07194328, 0.06948044,
        0.15524623, 0.10039029, 0.16133921, 0.07991634, 0.05605431]],
      dtype=float32)

In [11]:
x_train[:1].shape

(1, 28, 28)

In [12]:
x_train[0].shape

(28, 28)

In [13]:
y_train[0]

5

In [14]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)


In [15]:
loss_fn(y_train[:1], predictions).numpy()


1.8627429

In [16]:
y_train[:1]

array([5], dtype=uint8)

In [17]:
model.compile(optimizer='adam',loss=loss_fn,metrics=['accuracy'])


In [18]:
model.fit(x_train, y_train, epochs=5)


Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2977 - accuracy: 0.9141
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1417 - accuracy: 0.9581
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1069 - accuracy: 0.9679
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0882 - accuracy: 0.9732
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0739 - accuracy: 0.9771
